#!/bin/bash

#+SHORTDESC="Grabs a file until it hits a match."
#+ HELPTEXT="..."$'\n'
#++HELPTEXT="..."$'\n'
#+ SYNTAXTEXT="watchpot [options] jobname"$'\n'
#++SYNTAXTEXT="watchpot [options] -f filename"$'\n'
#++SYNTAXTEXT="watchpot [options] --jid jobid"$'\n'
#+ PARAMS="..."$'\n'
#+ VERSION="0.0.5"

if [ "$#" -eq 0 -o "$1" == "--help" -o "$1" == "--man" ]; then
  ${SWH_HELPER_SCRIPTS}/manForScript ${BASH_SOURCE[0]}
  exit 1
fi

if [ "$#" -lt 1 ];
then
  (>&2 echo "Error: requires one parameter at least")
  exit 1;
fi

TARGET="${@: -1}"
TGTTYPE="jobname"

if [ "$#" -ge 2 ] ; then
  if [ "${@: -2}" == "-f" ]; then
    TGTTYPE="filename"
  fi
  if [ "${@: -2}" == "--jid" ]; then
    TGTTYPE="jobid"
  fi
fi

TICKTIME=5
SILENT=0

#Other options:
while [ "$#" -ge 1 ]; do
   if [ "$1" == "-t" -o "$1" == "--tickTime" ]; then
      shift;
      TICKTIME=$1
   fi
   if [ "$1" == "-s" -o "$1" == "--silent" ]; then
      SILENT=1
   fi
   shift;
done

TGTFILE="$TARGET"

tmpfile=$(mktemp /tmp/estat2.XXXXXX)
exec 3>"$tmpfile"
rm $tmpfile

STARTDIR=$( pwd -P )

if [ "$TGTTYPE" == "jobname" -o "$TGTTYPE" == "jid" ]; then
  qstat -j ${TARGET} | sed $'s/[:][ ]\+/\t/g'| grep -v "^=" >&3

  sge_o_workdir=$(cat /dev/fd/3 | grep "^sge_o_workdir\>"   | head -n1 | cut -f2)
  stdout_path_list=$(cat /dev/fd/3 | grep "^stdout_path_list\>"   | head -n1 | cut -f2 | cut -f3 -d:)
  stdout_path_dir=$( dirname ${stdout_path_list} );
  
  echo "stdout_path_list=$stdout_path_list"
  echo "stdout_path_dir=$stdout_path_dir"
  
  cd ${sge_o_workdir}

  job_number=$(cat /dev/fd/3 | grep "^job_number\>" | head -n1 | cut -f2)
  job_name=$(cat /dev/fd/3 | grep "^job_name\>" | head -n1 | cut -f2)

  TGTFILE=${stdout_path_dir}/${job_number}_${job_name}.stdout

fi

TGTTS=$( date --reference=${TGTFILE} "+%s" )
TGTSTAMP=$( date --reference=${TGTFILE} "+%Y.%m.%d.%H%M%S" )
CURTS=$( date "+%s" )
CURSTAMP=$( date  "+%Y.%m.%d.%H%M%S" )
echo "watching file: ${TGTFILE} TIMESTAMP: ${TGTSTAMP} "
echo "current timestamp: ${CURSTAMP}, "$(( $CURTS - $TGTTS ))"s ago";

while [ "1" == "1" ]; do

    TICKCT=0
    while [ $( date --reference=${TGTFILE} "+%s" ) == ${TGTTS} ]; do
       echo -n ".";
       TICKCT=$(( $TICKCT + 1 ))
       if [ $(( $TICKCT % 10 )) == "0" ]; then
         echo -n " ";
         if [ $(( $TICKCT % 20 )) == "0" ]; then
            CURTS=$( date "+%s" )
            CURSTAMP=$( date  "+%Y.%m.%d.%H%M%S" )
            echo "watching file: ${TGTFILE} TIMESTAMP: ${TGTSTAMP}"
            echo "current timestamp: ${CURSTAMP}, "$(( $CURTS - $TGTTS ))"s ago";
         fi
       fi
       sleep ${TICKTIME}
    done

   TGTTS=$( date --reference=${TGTFILE} "+%s" )
   TGTSTAMP=$( date --reference=${TGTFILE} "+%Y.%m.%d.%H%M%S" )
   CURTS=$( date "+%s" )
   CURSTAMP=$( date  "+%Y.%m.%d.%H%M%S" )
   echo "------------------------------------------------";
   cat ${TGTFILE}

    sleep ${TICKTIME}
done










