#!/bin/bash

#+SHORTDESC="Read a fixed-width table from STDIN and convert to a delimited table (using tabs by default)"
#+ HELPTEXT="output goes to STDOUT. See also delim2fixed, which does the opposite conversion."$'\n'
#++HELPTEXT=" "$'\n'
#+ SYNTAXTEXT="cat mytable.txt | fixed2delim"$'\n'
#++SYNTAXTEXT=""$'\n'
#+ PARAMS="--help: displays syntax and help info."$'\n'
#++PARAMS="--man: synonym for --help."$'\n'
#++PARAMS="-d x or --delim x: make x the delimiter, by default it is a TAB "$'\n'
#++PARAMS="-v or --verbose: add verbose error reporting"$'\n'
#+ VERSION="0.0.5"

CURRENT_SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd -P )"
if [ "$1" == "--help" -o "$1" == "--man" ]; then
  ${CURRENT_SCRIPT_DIR}/../internal.manUtil/manForScript ${BASH_SOURCE[0]}
  exit 1
elif [ "$1" == "--manMarkdown" ]; then
  ${CURRENT_SCRIPT_DIR}/../internal.manUtil/manForScript --markdown ${BASH_SOURCE[0]}
  exit 1
fi

DELIM=$'\t'
VERBOSE="0"

while [ "$#" -gt 1 ];
do
      if [ "$1" == "--delim" -o "$1" == "-d" ];
      then
        shift;
        DELIM="$1";
      fi
      if [ "$1" == "-v" -o "$1" == "--verbose" ];
      then
        VERBOSE="1";
      fi
      shift;
done

if [ "$VERBOSE" == "1"  ]; then
  (>&2 echo "   DELIM  = \"${DELIM}\"");
fi


cat /dev/stdin | sed 's/\s\+/'"${DELIM}"'/g'

