#!/bin/bash

#GREPEXPR=$1
#shift
FILENAME="${@: -1}"
set -- "${@:1:$(($#-1))}"


if [ "${FILENAME: -3}" == ".gz" ]; then
  zcat ${FILENAME} | grep "$@" | less -S
else
  cat ${FILENAME} | grep "$@" | less -S
fi

