#!/bin/bash

#+SHORTDESC="Lists utilities available in the shareMisc module."
#+ HELPTEXT="shareMisc utility listing."$'\n'
#++HELPTEXT=" "$'\n'
#+ SYNTAXTEXT="shareMisc"$'\n'
#+ PARAMS="."$'\n'
#+ VERSION="0.0.5"

CURRENT_SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd -P )"
if [ "$1" == "--help" -o "$1" == "--man" ]; then
  ${CURRENT_SCRIPT_DIR}/../internal.manUtil/manForScript ${BASH_SOURCE[0]}
  exit 1
elif [ "$1" == "--manMarkdown" ]; then
  ${CURRENT_SCRIPT_DIR}/../internal.manUtil/manForScript --markdown ${BASH_SOURCE[0]}
  exit 1
fi

cat ${CURRENT_SCRIPT_DIR}/../doc/README





