#!/bin/bash

#+SHORTDESC="Linux Cheat Sheet"
#+ HELPTEXT="Get various useful unix commands and syntax tricks."$'\n'
#++HELPTEXT=" "$'\n'
#+ SYNTAXTEXT="shelp"$'\n'
#++SYNTAXTEXT="     (print list of topics)"$'\n'
#++SYNTAXTEXT="shelp [topic]"$'\n'
#++SYNTAXTEXT="     (print help on topic)"$'\n'
#+ PARAMS="--help: displays syntax and help info."$'\n'
#++PARAMS="--man: synonym for --help."$'\n'
#+ VERSION="0.0.5"

CURRENT_SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd -P )"
if [ "$1" == "--help" -o "$1" == "--man" ]; then
  ${CURRENT_SCRIPT_DIR}/../internal.manUtil/manForScript ${BASH_SOURCE[0]}
  exit 1
elif [ "$1" == "--manMarkdown" ]; then
  ${CURRENT_SCRIPT_DIR}/../internal.manUtil/manForScript --markdown ${BASH_SOURCE[0]}
  exit 1
fi

if [ "$#" -eq 0 ]; then
  echo "Help Topics:"
  while read line
  do
    DESCLINE=$(head -n2 $CURRENT_SCRIPT_DIR/shelpDoc/$line | tail -n1);
    #DESCLINE=${DESCLINE:1:${#DESCLINE}-2};
    echo "$line"$'\t'"$DESCLINE";
  done < <(ls $CURRENT_SCRIPT_DIR/shelpDoc/)
else
  cat $CURRENT_SCRIPT_DIR/shelpDoc/$1
fi
