#!/bin/bash

#+SHORTDESC="Trims leading whitespace."
#+ HELPTEXT="..."$'\n'
#++HELPTEXT="More Help Text"$'\n'
#+ SYNTAXTEXT="trimlw myfile.txt"$'\n'
#++SYNTAXTEXT="cat mystuff.txt | trimlw"$'\n'
#+ PARAMS="..."$'\n'
#+ VERSION="0.0.5"

CURRENT_SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd -P )"
if [ "$1" == "--help" -o "$1" == "--man" ]; then
  ${CURRENT_SCRIPT_DIR}/../internal.manUtil/manForScript ${BASH_SOURCE[0]}
  exit 1
elif [ "$1" == "--manMarkdown" ]; then
  ${CURRENT_SCRIPT_DIR}/../internal.manUtil/manForScript --markdown ${BASH_SOURCE[0]}
  exit 1
fi

sed 's/^[[:space:]]*//g' < "${1:-/dev/stdin}"
